config/routes.rb
Clicker::Application.routes.draw do

  devise_for :users, :skip => :registerable

  devise_scope :user do
    match '/admin/users', to: 'admin/users#create', via: :post
  end

  resources :homes

  resources :courses do
    member do
      post :add
    end
  end

  resources :students

  resources :teachers

  resources :profiles

  resources :interactive_items

  namespace :admin do

    get '/' => 'admins#index'
    resources :admins

    resources :courses do

      resources :interactive_items do

        resources :attendances

        resources :quizzes

        resources :polls

      end

    end

    resources :students

    resources :teachers

    resources :users


  end


  root to: "homes#index"


end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < Admin::AdminsController

  def index
    @teachers = User.with_role(:teacher, :any).decorate
  end

  def new
    @teacher = User.new
  end

  def edit
    @teacher = User.find(params[:id])
  end

  def destroy
    @teacher = User.find(params[:id])
    @teacher.destroy
    flash[:success] = "Teacher Deleted Successfully"
    redirect_to admin_teachers_path
  end

  private

  def teacher_params
    params.require(:user).permit(:first_name,:last_name, :email, :username, :password, :con)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
end

app/helpers/admin/teachers_helper.rb
module Admin::TeachersHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/teachers/_form.html.haml
.card.card-container
  %h2
    = @teacher.new_record? ? "Add Teacher" :  "Edit Teacher"
  -#= simple_form_for([:admin, @student], :url => admin_students_path, :method => :post, :html => {:class => 'form-signin'}) do |f|
  = simple_form_for([:admin, @teacher], :html => {:class => 'form-signin'}) do |f|
    = f.error_notification
    .form-group
      = f.input :first_name, required: true, autofocus: true, :class => 'form-control'
      = f.input :last_name, required: true, :class => 'form-control'
      = f.input :username, required: true, :class => 'form-control'
      = hidden_field_tag "user[type]", "teacher"
      = f.input :email, :class => 'form-control'
      = f.input :password, required: true, :class => 'form-control'
      = f.input :password_confirmation, required: true, :class => 'form-control'
    .form-actions
      = f.button :submit, "Submit"

app/views/admin/teachers/edit.html.haml
= render "layouts/admin_menu"
= render "admin/teachers/form"

app/views/admin/teachers/index.html.haml
= render "layouts/admin_menu"
#page-wrapper
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          %i.fa.fa-bar-chart-o.fa-fw
          All Teachers
          %span
            = link_to 'Add New', new_admin_teacher_path, :class => "btn btn-primary btn-sm"
        / /.panel-heading
        .panel-body
          .row
            .col-lg-12
              .table-responsive
                %table.table.table-bordered.table-hover.table-striped
                  %thead
                    %tr
                      %th #
                      %th Name
                      %th ID
                      %th Joined
                      %th Actions
                  %tbody
                    - @teachers.each_with_index do |teacher, index|
                      %tr
                        %td
                          = index + 1
                        %td
                          = teacher.name
                        %td
                          = teacher.email.blank? ? teacher.username : teacher.email
                        %td
                          = teacher.joined_at
                        %td
                          = link_fa_to("edit", "", edit_admin_teacher_path(teacher))
                          = link_to 'Delete',url_for(action: :destroy,id: teacher.id),method: :delete, data: {confirm: "Are you sure?"}

app/views/admin/teachers/new.html.haml
= render "layouts/admin_menu"
= render "admin/teachers/form"