config/routes.rb
Clicker::Application.routes.draw do

  devise_for :users, :skip => :registerable

  devise_scope :user do
    match '/admin/users', to: 'admin/users#create', via: :post
  end

  resources :homes

  resources :courses do
    member do
      post :add
    end
  end

  resources :students

  resources :teachers

  resources :profiles

  resources :interactive_items

  namespace :admin do

    get '/' => 'admins#index'
    resources :admins

    resources :courses do

      resources :interactive_items do

        resources :attendances

        resources :quizzes

        resources :polls

      end

    end

    resources :students

    resources :teachers

    resources :users


  end


  root to: "homes#index"


end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::AdminsController

  def index
    @students = User.with_role(:student, :any).decorate
  end

  def new
    @student = User.new
  end

  def edit
    @student = User.find(params[:id])
  end


  def destroy
    @student = User.find(params[:id])
    @student.destroy
    flash[:success] = "Student Deleted Successfully"
    redirect_to admin_students_path
  end

  private

  def student_params
    params.require(:user).permit(:first_name,:last_name, :email, :username, :password, :con)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/helpers/admin/students_helper.rb
module Admin::StudentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/students/_form.html.haml
.card.card-container
  %h2
    = @student.new_record? ? "Add Student" :  "Edit Student"
  -#= simple_form_for([:admin, @student], :url => admin_students_path, :method => :post, :html => {:class => 'form-signin'}) do |f|
  = simple_form_for([:admin, @student], :html => {:class => 'form-signin'}) do |f|
    = f.error_notification
    .form-group
      = f.input :first_name, required: true, autofocus: true, :class => 'form-control'
      = f.input :last_name, required: true, :class => 'form-control'
      = f.input :username, required: true, :class => 'form-control'
      = hidden_field_tag "user[type]", "student"
      = f.input :email, :class => 'form-control'
      = f.input :password, required: true, :class => 'form-control'
      = f.input :password_confirmation, required: true, :class => 'form-control'
    .form-actions
      = f.button :submit, "Submit"

app/views/admin/students/edit.html.haml
= render "layouts/admin_menu"
= render "admin/students/form"

app/views/admin/students/index.html.haml
= render "layouts/admin_menu"
#page-wrapper
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          %i.fa.fa-bar-chart-o.fa-fw
          All Students
          %span
            = link_to 'Add New', new_admin_student_path, :class => "btn btn-primary btn-sm"
        / /.panel-heading
        .panel-body
          .row
            .col-lg-12
              .table-responsive
                %table.table.table-bordered.table-hover.table-striped
                  %thead
                    %tr
                      %th #
                      %th Name
                      %th ID
                      %th Joined
                      %th Actions
                  %tbody
                    - @students.each_with_index do |student, index|
                      %tr
                        %td
                          = index + 1
                        %td
                          = student.name
                        %td
                          = student.email.blank? ? student.username : student.email
                        %td
                          = student.joined_at
                        %td
                          = link_fa_to("edit", "", edit_admin_student_path(student))
                          = link_to 'Delete',url_for(action: :destroy,id: student.id),method: :delete, data: {confirm: "Are you sure?"}

app/views/admin/students/new.html.haml
= render "layouts/admin_menu"
= render "admin/students/form"