config/routes.rb
Clicker::Application.routes.draw do

  devise_for :users, :skip => :registerable

  devise_scope :user do
    match '/admin/users', to: 'admin/users#create', via: :post
  end

  resources :homes

  resources :courses do
    member do
      post :add
    end
  end

  resources :students

  resources :teachers

  resources :profiles

  resources :interactive_items

  namespace :admin do

    get '/' => 'admins#index'
    resources :admins

    resources :courses do

      resources :interactive_items do

        resources :attendances

        resources :quizzes

        resources :polls

      end

    end

    resources :students

    resources :teachers

    resources :users


  end


  root to: "homes#index"


end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

  belongs_to :user
  belongs_to :course
  belongs_to :interactive_item

  has_many :user_attendances, :dependent => :destroy

end

app/models/course.rb
class Course < ActiveRecord::Base

  belongs_to :course_creator, class_name: "User"
  has_many :user_courses
  has_many :interactive_items, dependent: :destroy

  validates :user_id, presence: true
  validates :title, presence: true, :uniqueness => true
  # validates :courseId, presence: true, :uniqueness => true
  # validates :start_date, presence: true
  # validates :end_date, presence: true
  # validate :date_cannot_be_in_past

  before_save :add_search_terms


  private

  def add_search_terms
    # self.search_terms = self.courseId.downcase + ' ' + self.title.downcase
    self.search_terms = self.title.downcase
  end

  def date_cannot_be_in_past
    errors.add(:start_date, "start date can't be in the past") if self.start_date < Date.today
    errors.add(:end_date, "end date can't be in the past") if self.end_date < Date.today
  end


end

app/models/interactive_item.rb
class InteractiveItem < ActiveRecord::Base

  belongs_to :interactable, polymorphic: true
  belongs_to :user
  belongs_to :course

  has_many :attendances, :dependent => :destroy
  has_many :quizzes, :dependent => :destroy
  has_many :polls, :dependent => :destroy
  has_many :user_attendances, dependent: :destroy

  validates :interactable_id, presence: true
  validates :interactable_type, presence: true
  validates :course_id, presence: true
  validates :user_id, presence: true
  validates :for_date, presence: true

  INTERACTIVE_TYPES = ["ATTENDANCE", "QUIZ", "POLL"]


  def build_item(type ,klass, user, item_params, course)
    if type === "Attendance"
      klass.new(course: course, user: user)
    elsif type === "Quiz"
      klass.new(course: course, user: user, :title => item_params[:title].to_s, :time_limit => item_params[:time_limit].to_i)
    elsif type === "Poll"
      klass.new(course: course, user: user, :title => item_params[:title].to_s)
    end
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base

  belongs_to :user
  belongs_to :course
  belongs_to :interactive_item

  validates :title, presence: true, :uniqueness => true

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base

  belongs_to :user
  belongs_to :course
  belongs_to :interactive_item

  # validates :type, presence: true
  validates :title, presence: true

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :login

  rolify

  devise :database_authenticatable,
         # :registerable,:recoverable,
         :rememberable, :trackable, :validatable, :authentication_keys => [:login]


  has_many :courses
  has_many :user_courses, dependent: :destroy
  has_many :interactive_items, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :quizzes, dependent: :destroy
  has_many :polls, dependent: :destroy
  has_many :user_attendances, dependent: :destroy

  before_save :add_search_terms

  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }


  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def is_present(user_attendances, user)
    if user_attendances.where('user_id = ?', user.id).blank?
      return false
    else
      return true
    end
  end

  private

  def add_search_terms
    self.search_terms = self.first_name.downcase + ' ' + self.last_name.downcase
  end

  def email_required?
    false
  end

end

app/models/user_attendance.rb
class UserAttendance < ActiveRecord::Base

  belongs_to :user
  belongs_to :interactive_item
  belongs_to :attendance

end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base

  belongs_to :course
  belongs_to :user

  validates :user_id, presence: true
  validates :course_id, presence: true

  validate :can_be_registered


  private

  def can_be_registered
    errors.add(:course_id, "You are already registered in this course") unless UserCourse.where('user_id = ? and course_id = ?', self.user_id, self.course_id).blank?
    if Course.where('id = ?', self.course_id).first
      errors.add(:course_id, "Course Limit Reached") if UserCourse.where('course_id = ?', self.course_id).count >= Course.where('id = ?', self.course_id).first.limit
    else
      errors.add(:course_id, "No Such Course Exist")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  protected

  def is_admin
    redirect_to root_path unless current_user.has_role? :admin
  end

  def is_admin_or_teacher
    unless current_user.has_role? :admin or current_user.has_role? :teacher
      redirect_to root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
  end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def add
    @course = Course.find(params[:id])
    render :json => UserCourse.create!(:user => current_user, :course => @course)
  end

  private

  def course_params
    params.require(:course).permit(:title, :courseId, :limit, :start_date, :end_date)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index

  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def edit
    @profile = current_user
  end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :email, :username, :password, :con)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_fa_to(icon_name, text, link)
    link_to content_tag(:i, text, :class => "fa fa-#{icon_name}"), link
  end

  def item_title(item)
    if item.class.name === "Quiz" || item.class.name === "Poll"
      item.title
    else
      nil
    end
  end

  def check_title_required(item, new_record)
    if new_record
      return false
    else
      if item.class.name === "Quiz" || item.class.name === "Poll"
        return true
      else
        return false
      end
    end
  end

  def item_time_limit(item)
    if item.class.name === "Quiz"
      item.time_limit
    else
      nil
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper

  def can_create_course(user)
    if current_user.has_role? :teacher or current_user.has_role? :admin
      return true
    else
      return false
    end
  end

  def can_create_item(user)
    if current_user.has_role? :teacher or current_user.has_role? :admin
      return true
    else
      return false
    end
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/admins/index.html.haml
= render "layouts/admin_menu"
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header Dashboard
  .row
    .col-lg-3.col-md-6
      .panel.panel-primary
        .panel-heading
          .row
            .col-xs-3
              %i.fa.fa-user.fa-fw.fa-3x
            .col-xs-9.text-right
              .huge
                = @students.count
              %div Total Students
        %a{:href => "/admin/students"}
          .panel-footer
            %span.pull-left View Details
            %span.pull-right
              %i.fa.fa-arrow-circle-right
            .clearfix
    .col-lg-3.col-md-6
      .panel.panel-green
        .panel-heading
          .row
            .col-xs-3
              %i.fa.fa-user.fa-fw.fa-3x
            .col-xs-9.text-right
              .huge
                = @teachers.count
              %div Total Teachers
        %a{:href => "/admin/teachers"}
          .panel-footer
            %span.pull-left View Details
            %span.pull-right
              %i.fa.fa-arrow-circle-right
            .clearfix
    .col-lg-3.col-md-6
      .panel.panel-green
        .panel-heading
          .row
            .col-xs-3
              %i.fa.fa-user.fa-fw.fa-3x
            .col-xs-9.text-right
              .huge
                = @courses.count
              %div Total Courses
        %a{:href => "/admin/courses"}
          .panel-footer
            %span.pull-left View Details
            %span.pull-right
              %i.fa.fa-arrow-circle-right
            .clearfix

app/views/layouts/_admin_menu.html.haml
- if current_user.has_role? :admin
  %nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
    .navbar-default.sidebar{:role => "navigation"}
      .sidebar-nav.navbar-collapse
        %ul#side-menu.nav
          %li
            %a{:href => "/admin"}
              %i.fa.fa-dashboard.fa-fw
              Dashboard
          %li
            %a{:href => "#"}
              %i.fa.fa-bar-chart-o.fa-fw
              Students
            %ul.nav.nav-second-level
              %li
                %a{:href => "/admin/students"} All Students
          %li
            %a{:href => "#"}
              %i.fa.fa-bar-chart-o.fa-fw
              Teachers
            %ul.nav.nav-second-level
              %li
                %a{:href => "/admin/teachers"} All Teachers
          %li
            %a{:href => "#"}
              %i.fa.fa-bar-chart-o.fa-fw
              Courses
            %ul.nav.nav-second-level
              %li
                %a{:href => "/admin/courses"} All Courses

- elsif current_user.has_role? :teacher
  = render "layouts/teachers_menu"

app/views/layouts/_footer.html.haml
%p
  -#\© Clicker. All Rights Reserved

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top(ng-controller="HeaderCtrl"){:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"}
        = image_tag("common/logo.png", height: '20px', width: '20px')
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav
          %li(ng-repeat = "header in headers")
            %a{:href => "#"} {{header}}
          - if current_user.has_role? :admin
            %li
              %a{:href => "/admin"} Admin

      %form.navbar-form.navbar-left{:role => "search"}
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}/
      %ul.nav.navbar-nav.navbar-right

        - if user_signed_in?
          %li
            = link_to "#{current_user.decorate.name}", edit_profile_path(current_user)

          %li
            = link_to('Logout', destroy_user_session_path, :method => :delete)

        - else
          = link_to('Login', new_user_session_path)

    / /.navbar-collapse
  / /.container

app/views/layouts/_left_menu.html.haml
- if current_user.has_role? :student
  = render "layouts/students_menu"
- elsif current_user.has_role? :teacher
  = render "layouts/teachers_menu"
- elsif current_user.has_role? :admin
  = render "layouts/admin_menu"

app/views/layouts/_students_menu.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
  .navbar-default.sidebar{:role => "navigation"}
    .sidebar-nav.navbar-collapse
      %ul#side-menu.nav
        %li
          %a{:href => "/"}
            %i.fa.fa-dashboard.fa-fw
            Dashboard
        %li
          %a{:href => "#"}
            %i.fa.fa-bar-chart-o.fa-fw
            Courses
          %ul.nav.nav-second-level
            %li
              %a{:href => "/courses"} All Courses

app/views/layouts/_teachers_menu.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
  .navbar-default.sidebar{:role => "navigation"}
    .sidebar-nav.navbar-collapse
      %ul#side-menu.nav
        %li
          %a{:href => "/"}
            %i.fa.fa-dashboard.fa-fw
            Dashboard
        %li
          %a{:href => "#"}
            %i.fa.fa-bar-chart-o.fa-fw
            Courses
          %ul.nav.nav-second-level
            %li
              %a{:href => "/courses"} All Courses

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Clicker"
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" }
    %meta{ :content => content_for?(:description) ? yield(:description) : "Clicker", :name => "description" }
    %link{ :href => "https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,300,700", :rel => "stylesheet", :type => "text/css" }
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)

  %body(ng-app="Clicker"){:id => "#{params[:controller]}"}
    #wrapper
      #header-wrapper
        #header.container
          = render '/layouts/header'
        #menu.container
          - flash.each do |key, value|
            %div{:class => "alert alert-#{key}"}= value
          = render '/layouts/menu'
      #main.container{ :role => "main" }
        = yield

    #footer
      = render "/layouts/footer"